language: go
go:
  - 1.8

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin

install:
  - go install
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script:
  - sh test.sh
